// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type LoginReply struct {
	Message string `json:"token"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UserDetailReply struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}
